import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 460 } })
await p.goto(process.env.BASE + '/mri/gradient-echo', { waitUntil: 'networkidle' })
await p.waitForTimeout(900)
await p.locator('.m5-nav').screenshot({ path: '/tmp/nav-desktop.png' })
const p2 = await b.newPage({ viewport: { width: 390, height: 500 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
await p2.goto(process.env.BASE + '/mri/gradient-echo', { waitUntil: 'networkidle' })
await p2.waitForTimeout(900)
await p2.locator('.m5-nav').screenshot({ path: '/tmp/nav-mobile.png' })
const p3 = await b.newPage({ viewport: { width: 1440, height: 300 } })
await p3.goto(process.env.BASE + '/mri-lab/learn/t1-spin-echo', { waitUntil: 'networkidle' })
await p3.waitForTimeout(800)
await p3.locator('.lx-bar').screenshot({ path: '/tmp/nav-lesson.png' })
console.log('ok'); await b.close()
