import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs=[];
p.on('pageerror', e => errs.push({ m: String(e.message).slice(0,300), s: String(e.stack||'').split('\n').slice(0,8).join('\n').slice(0,900) }));
await p.goto('http://localhost:5199/visual-lab', { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
await p.getByRole('link', { name: /Open the laboratory/i }).nth(2).click();
await p.waitForTimeout(3500);
const st = await p.evaluate(()=>({ url: location.pathname, rootKids: document.getElementById('root')?.children.length }));
console.log(JSON.stringify({ st, errs }, null, 1));
await b.close();
