/**
 * Module 13 — Ultrasound Artefacts.
 *
 * The artefact workshop. Every artefact is generated by breaking the machine
 * assumption that causes it: the scene shows the true physics and beam path,
 * and the B-mode panel beside it shows what the machine drew. Enhancement and
 * shadowing genuinely EMERGE from the attenuation model; beam-path artefacts
 * are shown as the extra targets the machine placed, with the reveal overlay
 * exposing the difference between the true path and the assumed straight line.
 */

import { useCallback, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

import { BMode, type BModeScene, type BModeSettings } from '../components/BMode'
import { ControlGroup, Slider, StageFlash, Toggle, useFlash } from '../components/Controls'
import {
  GuidedCaption,
  GuidedTransport,
  Predict,
  useClock,
  useGuided,
  type GuidedStep,
} from '../components/Guided'
import { UsIcon } from '../components/icons'
import {
  FocusHide,
  ModelNote,
  MoreDetail,
  Readout,
  SourceNote,
  TrapNote,
  UsLab,
} from '../components/Layout'
import { TeachingPanel, type Delta } from '../components/Teaching'
import {
  ArtefactStage,
  type ArtefactPhase,
  type ArtefactSceneKind,
} from '../scenes/ArtefactStage'
import { apparentDepthMm, attenuationDb, maxPrfHz } from '../engine'

/* ------------------------------------------------------------------ *
 * The artefact catalogue
 * ------------------------------------------------------------------ */

export type ArtefactId =
  | 'shadowing'
  | 'enhancement'
  | 'reverberation'
  | 'ringdown'
  | 'mirror'
  | 'refraction'
  | 'speed'
  | 'sidelobe'
  | 'gratinglobe'
  | 'beamwidth'
  | 'slicethickness'
  | 'rangeambiguity'
  | 'speckle'
  | 'anisotropy'
  | 'aliasing'
  | 'blooming'
  | 'flash'
  | 'twinkle'

type ArtefactEntry = {
  id: ArtefactId
  name: string
  group: string
  /** The physical situation on the stage. */
  setup: string
  /** What the sound actually did. */
  mechanism: string
  /** The machine assumption that was violated. */
  assumption: string
  /** How to recognise it on the image. */
  recognition: string
  /** How to remove it — or exploit it. */
  fix: string
  /** The examination wording that catches people. */
  trap: string
  sceneKind: ArtefactSceneKind
  deltas: Delta[]
}

const ARTEFACTS: ArtefactEntry[] = [
  {
    id: 'shadowing',
    name: 'Acoustic shadowing',
    group: 'Attenuation',
    setup: 'A gallstone and a pocket of bowel gas at the same depth in soft tissue.',
    mechanism:
      'Almost all of the beam is reflected or absorbed at the stone or gas surface, so nothing is left to interrogate the tissue beyond it. A stone gives a sharp, clean shadow; gas reverberates, filling its shadow with noise — a dirty shadow.',
    assumption: 'Attenuation is uniform and predictable',
    recognition: 'A dark band extending from the structure to the bottom of the image, clean behind stone or bone, noisy behind gas.',
    fix: 'Image around the structure from another window. The shadow itself is diagnostic — it confirms a strong attenuator.',
    trap: '“Acoustic shadowing can be caused by both cysts and gallstones” is FALSE (QBank Q382). A cyst causes posterior ENHANCEMENT; a stone causes shadowing. They are opposite failures of the same assumption.',
    sceneKind: 'shadowing',
    deltas: [
      { label: 'Attenuation at the surface ↑↑', dir: 'warn' },
      { label: 'Energy beyond the structure ↓', dir: 'down' },
      { label: 'Echoes from deeper tissue ↓', dir: 'down' },
      { label: 'Stone → clean · gas → dirty', dir: 'flat' },
    ],
  },
  {
    id: 'enhancement',
    name: 'Posterior enhancement',
    group: 'Attenuation',
    setup: 'A simple fluid-filled cyst in attenuating parenchyma.',
    mechanism:
      'Fluid removes almost no energy, so the beam that crossed the cyst arrives at the deeper tissue stronger than its neighbours. The machine, compensating for the attenuation it EXPECTED, over-brightens that column.',
    assumption: 'Attenuation is uniform and predictable',
    recognition: 'A bright band immediately deep to an anechoic, thin-walled lesion.',
    fix: 'Nothing to fix — exploit it. Enhancement is a reassuring sign that a lesion is truly fluid.',
    trap: 'The question bank pairs this with shadowing: enhancement is the LOW-attenuation failure, shadowing the HIGH-attenuation one. Never let a stem attribute shadowing to a cyst.',
    sceneKind: 'enhancement',
    deltas: [
      { label: 'Attenuation inside the cyst ↓↓', dir: 'down' },
      { label: 'Beam intensity beyond it ↑', dir: 'up' },
      { label: 'Displayed brightness beyond it ↑', dir: 'up' },
      { label: 'TGC assumed uniform loss', dir: 'warn' },
    ],
  },
  {
    id: 'reverberation',
    name: 'Reverberation & comet-tail',
    group: 'Beam path',
    setup: 'Two strong, parallel, closely spaced interfaces near the probe.',
    mechanism:
      'The pulse rattles back and forth between the two interfaces. Every round trip adds the same extra time, so the machine draws a stack of copies at exactly equal spacing, each fainter than the last. Comet-tail is the tightly spaced version from a small strong reflector.',
    assumption: 'Sound travels in straight lines, once',
    recognition: 'Equally spaced repeating bands deep to a strong interface, fading with depth.',
    fix: 'Change the angle of insonation, or use harmonic imaging — the clutter has little harmonic content.',
    trap: '“Comet-tail and ring-down artefacts are both caused by reverberation” is FALSE (QBank Q412). Only comet-tail is a reverberation. Ring-down is a resonant emission.',
    sceneKind: 'reverberation',
    deltas: [
      { label: 'Each round trip → same Δt', dir: 'flat' },
      { label: 'Copies at equal spacing', dir: 'flat' },
      { label: 'Brightness of each copy ↓', dir: 'down' },
      { label: 'Angle change → artefact ↓', dir: 'up' },
    ],
  },
  {
    id: 'ringdown',
    name: 'Ring-down',
    group: 'Beam path',
    setup: 'A small volume of fluid trapped between gas bubbles.',
    mechanism:
      'The pulse sets the trapped fluid resonating, and it re-radiates a CONTINUOUS signal back to the probe. The machine converts that unbroken stream of sound into an unbroken bright line — not the discrete, equally spaced bands of reverberation.',
    assumption: 'Echoes stop when the pulse has passed',
    recognition: 'A continuous bright streak extending down from gas, with no discrete banding.',
    fix: 'Recognise it as a gas signature. It is useful evidence of pneumobilia, emphysematous infection or bowel gas.',
    trap: 'QBank Q412 draws exactly this distinction: ring-down is NOT simple reverberation. A stem that lumps them together is false.',
    sceneKind: 'ringdown',
    deltas: [
      { label: 'Trapped fluid resonates', dir: 'flat' },
      { label: 'Continuous emission → solid line', dir: 'flat' },
      { label: 'Discrete bands — absent', dir: 'down' },
      { label: 'Gas signature — diagnostic', dir: 'up' },
    ],
  },
  {
    id: 'mirror',
    name: 'Mirror image',
    group: 'Beam path',
    setup: 'A liver lesion above the diaphragm — a strong, smooth, curved reflector.',
    mechanism:
      'Part of the beam reflects off the diaphragm, strikes the lesion, and returns by the same indirect route. The machine times the long detour, assumes a straight line, and draws a second copy of the lesion BEYOND the diaphragm — apparently inside the lung.',
    assumption: 'Sound travels in straight lines',
    recognition: 'A duplicate of a real structure, equidistant beyond a strong specular interface, moving with the original.',
    fix: 'Change the angle of insonation; the copy moves or vanishes while real anatomy stays put.',
    trap: 'The copy appears DEEP to the reflector, never superficial to it — the detour can only ever add time.',
    sceneKind: 'mirror',
    deltas: [
      { label: 'Path length via mirror ↑', dir: 'up' },
      { label: 'Measured echo time ↑', dir: 'up' },
      { label: 'Copy placed beyond the reflector', dir: 'warn' },
      { label: 'Angle change → copy moves', dir: 'flat' },
    ],
  },
  {
    id: 'refraction',
    name: 'Refraction artefact',
    group: 'Beam path',
    setup: 'A curved fluid structure — the edge of a cyst, or the rectus muscles above the pelvis.',
    mechanism:
      'At the curved edge the beam crosses obliquely between media of different speed and is bent away from its original line. The edge rays are deviated, leaving narrow EDGE SHADOWS; a target reached by a bent beam is drawn on the straight line the machine assumed, laterally misplaced or duplicated.',
    assumption: 'Sound travels in straight lines',
    recognition: 'Thin shadows from the lateral edges of curved structures; duplicated deep structures in the midline pelvis.',
    fix: 'Change the window or approach angle. Reducing the transmit frequency does NOT help — refraction does not depend on frequency.',
    trap: '“Refraction artefacts can be reduced by reducing the transmit frequency” is FALSE (QBank Q382). Bending depends on the angle and the two speeds only.',
    sceneKind: 'refraction',
    deltas: [
      { label: 'Oblique incidence + Δc → bend', dir: 'warn' },
      { label: 'Edge rays deviated → edge shadow', dir: 'down' },
      { label: 'Lateral misplacement / duplication', dir: 'warn' },
      { label: 'Frequency → no effect', dir: 'flat' },
    ],
  },
  {
    id: 'speed',
    name: 'Speed-displacement error',
    group: 'Speed & timing',
    setup: 'A reflector beneath a thick layer of fat, which carries sound at 1450 m/s rather than 1540.',
    mechanism:
      'The echo spends longer in the slow fat than the machine allows for. Converting the late arrival with the assumed 1540 m/s places the reflector too DEEP. Faster overlying tissue would place it too shallow. The displacement is axial, along the beam.',
    assumption: 'Speed is 1540 m/s everywhere',
    recognition: 'A stepped or displaced interface where the overlying tissue changes — classically a broken diaphragm outline beneath focal fat.',
    fix: 'Recognise it; some machines offer a fat-corrected speed. It also degrades focusing, so lesions in steatotic livers blur.',
    trap: 'The reflector under SLOW tissue appears too DEEP — candidates habitually reverse this. Late echo = extra assumed distance.',
    sceneKind: 'speed',
    deltas: [
      { label: 'True speed ↓ → echo late', dir: 'down' },
      { label: 'Assumed 1540 m/s unchanged', dir: 'flat' },
      { label: 'Drawn depth ↑ (too deep)', dir: 'warn' },
      { label: 'Displacement is axial', dir: 'flat' },
    ],
  },
  {
    id: 'sidelobe',
    name: 'Side-lobe artefact',
    group: 'Beam geometry',
    setup: 'A full bladder with strong off-axis reflectors — bowel gas — beside the main beam.',
    mechanism:
      'The transducer emits weak lobes off the main axis. When a side lobe strikes a STRONG reflector, its echo is loud enough to detect — and the machine, which assumes every echo came from the main beam, draws it on the main line: pseudo-debris inside the anechoic bladder.',
    assumption: 'Echoes come from the main beam only',
    recognition: 'Faint, curved, mobile echoes inside structures that should be anechoic, disappearing as the angle changes.',
    fix: 'Re-angle the probe, reduce gain, or use harmonic imaging — side-lobe energy is too weak to generate harmonics.',
    trap: 'Side lobes exist on EVERY transducer (single elements included). Grating lobes are the separate, array-specific species.',
    sceneKind: 'sidelobe',
    deltas: [
      { label: 'Off-axis lobe hits strong reflector', dir: 'warn' },
      { label: 'Echo assigned to main line', dir: 'warn' },
      { label: 'Pseudo-debris in anechoic spaces', dir: 'flat' },
      { label: 'Harmonics → side-lobe clutter ↓', dir: 'up' },
    ],
  },
  {
    id: 'gratinglobe',
    name: 'Grating-lobe artefact',
    group: 'Beam geometry',
    setup: 'An array transducer whose regular element spacing sprays energy at discrete symmetric angles.',
    mechanism:
      'The PERIODIC spacing of array elements creates constructive interference at large, predictable off-axis angles — grating lobes. Like side lobes they paint off-axis structures onto the main line, but they sit at larger angles and are a property of arrays specifically.',
    assumption: 'Echoes come from the main beam only',
    recognition: 'Ghost copies of strong lateral reflectors displaced across the image.',
    fix: 'Manufacturers suppress them with sub-wavelength element spacing (λ/2) and apodisation; the operator can change the angle.',
    trap: 'Side lobes: every transducer. Grating lobes: ARRAYS only, from periodic element spacing. Stems love to swap the two.',
    sceneKind: 'gratinglobe',
    deltas: [
      { label: 'Periodic spacing → discrete lobes', dir: 'warn' },
      { label: 'Lobe angle ↑ vs side lobes', dir: 'up' },
      { label: 'Element pitch ↓ → lobes pushed out', dir: 'up' },
      { label: 'Apodisation → lobes ↓', dir: 'up' },
    ],
  },
  {
    id: 'beamwidth',
    name: 'Beam-width artefact',
    group: 'Beam geometry',
    setup: 'A small cyst at a depth where the unfocused beam has grown wider than the cyst itself.',
    mechanism:
      'Everything inside the beam at one instant is summed into one line of the image. When the beam is wider than the cyst, echoes from tissue BESIDE it are averaged into the cyst pixels — partial-volume debris.',
    assumption: 'The beam is infinitely thin',
    recognition: 'False low-level echoes inside small deep cysts, clearing when the focus is set to the lesion.',
    fix: 'Put the focal zone AT the lesion — lateral resolution is best at the focus.',
    trap: 'This is the lateral in-plane cousin of the slice-thickness artefact; the two stems are often set side by side.',
    sceneKind: 'beamwidth',
    deltas: [
      { label: 'Beam width at lesion ↑', dir: 'warn' },
      { label: 'Adjacent echoes averaged in', dir: 'warn' },
      { label: 'Focus at lesion → artefact ↓', dir: 'up' },
      { label: 'Lateral resolution ↔ beam width', dir: 'flat' },
    ],
  },
  {
    id: 'slicethickness',
    name: 'Slice-thickness artefact',
    group: 'Beam geometry',
    setup: 'The same small cyst — but the offender is the thickness of the slice OUT of the imaging plane.',
    mechanism:
      'The elevation plane is focused by a fixed lens, so away from its focus the slice is thick. Tissue in FRONT of and BEHIND the imaging plane is averaged into the image: partial-volume echoes fill small fluid spaces.',
    assumption: 'The image is an infinitely thin slice',
    recognition: 'Low-level echoes layering in small cysts, gallbladder or bladder — often mimicking sludge or debris.',
    fix: 'Elevation focus is fixed by the lens: move the patient or probe so the lesion sits at the lens focus, or use a matrix probe.',
    trap: 'Elevational resolution is the WORST of the three on a standard 1D array, and the operator cannot steer it electronically.',
    sceneKind: 'slicethickness',
    deltas: [
      { label: 'Slice thickness away from lens focus ↑', dir: 'warn' },
      { label: 'Out-of-plane echoes averaged in', dir: 'warn' },
      { label: 'Fixed lens → no electronic control', dir: 'flat' },
      { label: 'Matrix arrays → slice ↓', dir: 'up' },
    ],
  },
  {
    id: 'rangeambiguity',
    name: 'Range ambiguity',
    group: 'Speed & timing',
    setup: 'A deep reflector interrogated at a PRF too high for the depth being imaged.',
    mechanism:
      'The echo from the deep reflector is still travelling when the NEXT pulse is transmitted. The machine times every echo against the most recent pulse, so the late arrival is assigned to the new pulse and drawn at a falsely SHALLOW depth.',
    assumption: 'Every echo belongs to the most recent pulse',
    recognition: 'Faint deep structures appearing superimposed on shallow anatomy at high PRF or high frame-rate settings.',
    fix: 'Lower the PRF (increase the depth setting) so every echo returns before the next transmission.',
    trap: 'PRF is capped by depth: max PRF = c / 2d. That equation is the whole artefact.',
    sceneKind: 'rangeambiguity',
    deltas: [
      { label: 'PRF ↑ beyond c/2d', dir: 'warn' },
      { label: 'Deep echo arrives after next pulse', dir: 'warn' },
      { label: 'Drawn depth ↓ (too shallow)', dir: 'down' },
      { label: 'PRF ↓ → artefact cleared', dir: 'up' },
    ],
  },
  {
    id: 'speckle',
    name: 'Speckle',
    group: 'Texture',
    setup: 'Ordinary parenchyma: countless scatterers far smaller than the wavelength inside every resolution cell.',
    mechanism:
      'The wavelets scattered within one resolution cell interfere constructively and destructively. The grainy texture is that INTERFERENCE pattern — it is not a picture of the underlying microstructure, and it coarsens as resolution worsens.',
    assumption: 'Brightness maps real reflectors',
    recognition: 'The characteristic grain of every parenchymal organ; it moves with the probe, not with the tissue.',
    fix: 'Compounding and speckle-reduction filters average independent speckle patterns; some texture is clinically useful.',
    trap: '“Speckle is due to diffuse reflection at tissue boundaries” is FALSE (QBank Q412). It is interference between scattered wavelets.',
    sceneKind: 'speckle',
    deltas: [
      { label: 'Scatterers ≪ λ interfere', dir: 'flat' },
      { label: 'Resolution ↓ → grain coarser', dir: 'down' },
      { label: 'Compounding → speckle ↓', dir: 'up' },
      { label: 'Not microstructure', dir: 'warn' },
    ],
  },
  {
    id: 'anisotropy',
    name: 'Anisotropy',
    group: 'Texture',
    setup: 'A tendon — a strong, highly ordered, angle-dependent specular reflector.',
    mechanism:
      'Perpendicular to the fibres, the echoes return to the probe and the tendon is bright. A few degrees off, the specular echoes are deflected AWAY from the probe and the tendon turns falsely dark — mimicking a tear.',
    assumption: 'Echo strength reflects tissue, not geometry',
    recognition: 'A tendon or nerve darkening exactly where the beam is not perpendicular, recovering with heel–toe rocking.',
    fix: 'Rock the probe until the fibrillar pattern returns before calling pathology. Explored properly in the Reflection experiment.',
    trap: 'This is a GEOMETRY artefact, not attenuation. The tissue has not changed — your angle has.',
    sceneKind: 'anisotropy',
    deltas: [
      { label: 'Angle off 90° → echo misses probe', dir: 'warn' },
      { label: 'Displayed brightness ↓', dir: 'down' },
      { label: 'Heel–toe rock → brightness back', dir: 'up' },
      { label: 'Attenuation unchanged', dir: 'flat' },
    ],
  },
  {
    id: 'aliasing',
    name: 'Colour / spectral aliasing',
    group: 'Doppler',
    setup: 'Fast flow sampled by a pulsed Doppler system at a PRF whose Nyquist limit the shift exceeds.',
    mechanism:
      'A shift beyond PRF/2 cannot be represented and wraps to the opposite end of the scale: spectral traces wrap round the baseline, colour flips through the mosaic to the opposite hue in the fastest core.',
    assumption: 'Sampling is fast enough for the shift',
    recognition: 'Colour reversal WITHOUT an intervening black stripe of true zero flow; spectral wrap-around.',
    fix: 'Raise the PRF (scale), shift the baseline, lower the transmit frequency, or use CW Doppler. The full treatment lives in the Aliasing experiment.',
    trap: 'Raising the transmit frequency makes aliasing MORE likely (QBank Q413) — the shift grows with f₀.',
    sceneKind: 'doppler-aliasing',
    deltas: [
      { label: 'Shift > PRF/2 → wrap', dir: 'warn' },
      { label: 'PRF ↑ → aliasing ↓', dir: 'up' },
      { label: 'f₀ ↑ → aliasing ↑', dir: 'warn' },
      { label: 'True reversal keeps a black stripe', dir: 'flat' },
    ],
  },
  {
    id: 'blooming',
    name: 'Colour blooming',
    group: 'Doppler',
    setup: 'A vessel imaged with the colour gain set too high.',
    mechanism:
      'Colour pixels are painted wherever the Doppler signal beats the threshold. Excess gain lets weak, spurious signal through, so colour spills OVER the vessel wall into the surrounding tissue and the vessel looks falsely wide.',
    assumption: 'Colour marks true flow only',
    recognition: 'Colour extending past the greyscale vessel wall; it shrinks as the colour gain comes down.',
    fix: 'Turn colour gain down until random colour noise just disappears — the standard set-up rule.',
    trap: 'Blooming exaggerates vessel calibre and can bury a mural thrombus under colour.',
    sceneKind: 'doppler-blooming',
    deltas: [
      { label: 'Colour gain ↑↑', dir: 'warn' },
      { label: 'Colour spills past the wall', dir: 'warn' },
      { label: 'Apparent vessel width ↑', dir: 'up' },
      { label: 'Gain ↓ → truth restored', dir: 'up' },
    ],
  },
  {
    id: 'flash',
    name: 'Flash artefact',
    group: 'Doppler',
    setup: 'Power Doppler over moving tissue — a breathing patient, a moving probe, a beating heart nearby.',
    mechanism:
      'Power Doppler displays the STRENGTH of any Doppler signal and is exquisitely motion-sensitive. Bulk tissue or probe motion produces a strong low-frequency signal that splashes colour across the whole box.',
    assumption: 'Only blood moves',
    recognition: 'Sudden sheets of colour filling the box, synchronous with breathing, probe movement or cardiac pulsation.',
    fix: 'Hold the probe still, ask for a breath-hold, and use wall filters — at the cost of low-flow sensitivity.',
    trap: 'Power Doppler has no aliasing (no velocity scale to wrap) but pays for it with flash sensitivity.',
    sceneKind: 'doppler-flash',
    deltas: [
      { label: 'Bulk motion → strong signal', dir: 'warn' },
      { label: 'Colour splashed across the box', dir: 'warn' },
      { label: 'Wall filter ↑ → flash ↓', dir: 'up' },
      { label: 'Low-flow sensitivity ↓ as filter ↑', dir: 'down' },
    ],
  },
  {
    id: 'twinkle',
    name: 'Twinkle artefact',
    group: 'Doppler',
    setup: 'Colour Doppler behind a rough, strongly reflecting calculus.',
    mechanism:
      'The rough surface returns a rapidly fluctuating echo that the colour processor renders as a fast alternating mosaic — a shimmering tail deep to the stone, where no flow exists.',
    assumption: 'Colour marks true flow only',
    recognition: 'A rapidly alternating colour mosaic immediately behind a calculus, often stronger than its grey shadow.',
    fix: 'Exploit it: twinkle can reveal a ureteric or renal stone that is nearly invisible on B-mode.',
    trap: 'Twinkle is the artefact used FOR diagnosis (QBank on artefact exploitation) — a favourite “which is useful?” stem.',
    sceneKind: 'doppler-twinkle',
    deltas: [
      { label: 'Rough calculus → fluctuating echo', dir: 'flat' },
      { label: 'Colour mosaic behind the stone', dir: 'warn' },
      { label: 'Stone conspicuity ↑', dir: 'up' },
      { label: 'No true flow present', dir: 'flat' },
    ],
  },
]

const ARTEFACT_BY_ID = new Map(ARTEFACTS.map((entry) => [entry.id, entry]))
const GROUPS = ['Attenuation', 'Beam path', 'Speed & timing', 'Beam geometry', 'Texture', 'Doppler']

/* ------------------------------------------------------------------ *
 * State and guided steps
 * ------------------------------------------------------------------ */

type State = {
  artefactId: ArtefactId
  revealPath: boolean
  frequencyMHz: number
}

const DEFAULTS: State = {
  artefactId: 'shadowing',
  revealPath: false,
  frequencyMHz: 5,
}

const STEPS: GuidedStep<State>[] = [
  {
    id: 'assumptions',
    title: 'Four assumptions build every image',
    phase: 'assumptions',
    state: { artefactId: 'shadowing', revealPath: false },
    caption: (
      <>
        The machine believes four things: sound travels at <b>1540 m/s</b>, in{' '}
        <b>straight lines</b>, echoes come from the <b>main beam</b>, and attenuation is{' '}
        <b>predictable</b>. Every classic artefact is one of these beliefs being violated — that is
        the whole taxonomy.
      </>
    ),
  },
  {
    id: 'shadowing',
    title: 'Shadowing — too much energy removed',
    phase: 'demo',
    state: { artefactId: 'shadowing', revealPath: false },
    duration: 1.6,
    caption: (
      <>
        A stone reflects and absorbs nearly the whole beam, so nothing is left to image behind it: a{' '}
        <b>clean shadow</b>. Gas does the same but reverberates, so its shadow fills with noise — a{' '}
        <b>dirty shadow</b>. Watch the B-mode: the shadow <b>emerges</b> from the attenuation, it is
        not painted on.
      </>
    ),
  },
  {
    id: 'enhancement',
    title: 'Enhancement — too little energy removed',
    phase: 'demo',
    state: { artefactId: 'enhancement', revealPath: false },
    duration: 1.6,
    caption: (
      <>
        Fluid barely attenuates. The beam crossing the cyst arrives at the deeper tissue{' '}
        <b>stronger</b> than its neighbours, so the machine draws a <b>bright band</b> beyond it.
        Same violated assumption as shadowing — in the opposite direction.
      </>
    ),
  },
  {
    id: 'reverberation',
    title: 'Reverberation — the pulse takes extra round trips',
    phase: 'demo',
    state: { artefactId: 'reverberation', revealPath: true },
    duration: 1.8,
    caption: (
      <>
        Two strong parallel interfaces trap the pulse. Every extra round trip adds the{' '}
        <b>same extra time</b>, so the machine draws copies at <b>equal spacing</b>, each fainter.
        The amber path is what the sound did; the dashed cyan lines are where the machine thought
        each echo came from.
      </>
    ),
  },
  {
    id: 'mirror',
    title: 'Mirror image — a detour drawn as depth',
    phase: 'demo',
    state: { artefactId: 'mirror', revealPath: true },
    duration: 1.8,
    caption: (
      <>
        The beam bounces off the <b>diaphragm</b>, hits the lesion, and comes home the same way.
        The machine times the detour, assumes a straight line, and places a <b>copy beyond the
        mirror</b> — a lesion apparently in the lung.
      </>
    ),
  },
  {
    id: 'speed',
    title: 'Speed error — late echoes are drawn too deep',
    phase: 'demo',
    state: { artefactId: 'speed', revealPath: true },
    duration: 1.6,
    caption: () => {
      const apparent = apparentDepthMm(45, 1450) / 10
      return (
        <>
          Fat carries sound at <b>1450 m/s</b>, so the echo from 4.5 cm arrives late. Converted at
          the assumed 1540 m/s it is drawn at <b>{apparent.toFixed(2)} cm</b> — too deep. Slow
          tissue pushes structures deeper; fast tissue pulls them shallower.
        </>
      )
    },
  },
  {
    id: 'sidelobe',
    title: 'Side lobes — echoes from off the axis',
    phase: 'demo',
    state: { artefactId: 'sidelobe', revealPath: true },
    duration: 1.6,
    caption: (
      <>
        A weak <b>side lobe</b> finds bowel gas beside the bladder. Its echo is strong enough to
        detect, and the machine — believing every echo came from the <b>main beam</b> — draws
        pseudo-debris inside an organ that should be black.
      </>
    ),
  },
  {
    id: 'explore',
    title: 'Explore the rest of the catalogue',
    phase: 'free',
    state: { revealPath: true },
    caption: (
      <>
        The selector on the right holds the full catalogue — ring-down, refraction, grating lobes,
        beam-width and slice-thickness, range ambiguity, speckle, anisotropy and the Doppler family.
        Pick each one, read its <b>violated assumption</b>, and check the B-mode against the
        physics.
      </>
    ),
  },
]

/* ------------------------------------------------------------------ *
 * B-mode composition per artefact
 * ------------------------------------------------------------------ */

function bmodeSceneFor(id: ArtefactId): BModeScene {
  const base = { widthCm: 5, depthCm: 8, background: 0.34, backgroundAttenuation: 0.5 }
  switch (id) {
    case 'shadowing':
      return {
        ...base,
        targets: [
          // The stone: strongly attenuating — its clean shadow EMERGES.
          { x: -0.45, depthCm: 3.2, radiusCm: 0.35, echogenicity: 0.95, rim: 0.9, attenuation: 20, scatter: 0.25 },
          // The gas: also strongly attenuating, plus reverberant noise the
          // machine placed in its shadow — which is what makes it dirty.
          { x: 0.45, depthCm: 3.2, radiusCm: 0.35, echogenicity: 0.9, attenuation: 12, scatter: 0.9 },
          { x: 0.45, depthCm: 4.4, radiusCm: 0.28, echogenicity: 0.28, attenuation: 0.5, scatter: 1 },
          { x: 0.42, depthCm: 5.5, radiusCm: 0.24, echogenicity: 0.2, attenuation: 0.5, scatter: 1 },
          { x: 0.48, depthCm: 6.5, radiusCm: 0.22, echogenicity: 0.14, attenuation: 0.5, scatter: 1 },
        ],
      }
    case 'enhancement':
      return {
        ...base,
        targets: [
          // Low attenuation is ALL the cyst needs: the bright band appears by itself.
          { x: 0, depthCm: 3.2, radiusCm: 1.0, echogenicity: 0.02, attenuation: 0.02, scatter: 0.1 },
        ],
      }
    case 'reverberation':
      return {
        ...base,
        targets: [
          { x: -0.2, depthCm: 1.1, radiusCm: 0.12, halfWidthCm: 1.1, shape: 'box', echogenicity: 0.95, scatter: 0.2 },
          { x: -0.2, depthCm: 2.0, radiusCm: 0.12, halfWidthCm: 1.1, shape: 'box', echogenicity: 0.9, scatter: 0.2 },
          // The machine placed these: copies at equal spacing, ever fainter.
          { x: -0.2, depthCm: 2.9, radiusCm: 0.1, halfWidthCm: 1.0, shape: 'box', echogenicity: 0.55, scatter: 0.2 },
          { x: -0.2, depthCm: 3.8, radiusCm: 0.1, halfWidthCm: 0.95, shape: 'box', echogenicity: 0.34, scatter: 0.2 },
          { x: -0.2, depthCm: 4.7, radiusCm: 0.09, halfWidthCm: 0.9, shape: 'box', echogenicity: 0.2, scatter: 0.2 },
        ],
      }
    case 'ringdown':
      return {
        ...base,
        targets: [
          { x: 0.3, depthCm: 1.5, radiusCm: 0.3, echogenicity: 0.92, attenuation: 8, scatter: 0.8 },
          // The continuous resonant line: one unbroken bright streak.
          { x: 0.3, depthCm: 4.6, radiusCm: 2.9, halfWidthCm: 0.09, shape: 'box', echogenicity: 0.75, attenuation: 0.4, scatter: 0.35 },
        ],
      }
    case 'mirror':
      return {
        ...base,
        targets: [
          { x: 0, depthCm: 4.8, radiusCm: 0.18, halfWidthCm: 2.4, shape: 'box', echogenicity: 0.98, rim: 0.6, scatter: 0.15 },
          { x: 0.3, depthCm: 3.1, radiusCm: 0.45, echogenicity: 0.75, scatter: 0.7 },
          // The machine placed this copy beyond the mirror.
          { x: 0.3, depthCm: 6.5, radiusCm: 0.45, echogenicity: 0.42, scatter: 0.7 },
        ],
      }
    case 'refraction':
      return {
        ...base,
        targets: [
          { x: -0.1, depthCm: 2.6, radiusCm: 1.0, echogenicity: 0.03, attenuation: 0.03, scatter: 0.1 },
          // Narrow strongly attenuating strips stand in for the deviated edge
          // rays, so the thin edge shadows appear in the reconstruction.
          { x: -0.52, depthCm: 2.9, radiusCm: 0.5, halfWidthCm: 0.07, shape: 'box', echogenicity: 0.1, attenuation: 9, scatter: 0.3 },
          { x: 0.32, depthCm: 2.9, radiusCm: 0.5, halfWidthCm: 0.07, shape: 'box', echogenicity: 0.1, attenuation: 9, scatter: 0.3 },
          { x: 0.52, depthCm: 5.4, radiusCm: 0.3, echogenicity: 0.7, scatter: 0.5 },
          // The duplicate the straight-line assumption created.
          { x: 0.28, depthCm: 5.55, radiusCm: 0.3, echogenicity: 0.4, scatter: 0.5 },
        ],
      }
    case 'speed': {
      const apparentCm = apparentDepthMm(45, 1450) / 10
      return {
        ...base,
        targets: [
          { x: 0, depthCm: 1.2, radiusCm: 1.2, halfWidthCm: 2.5, shape: 'box', echogenicity: 0.42, attenuation: 0.6, scatter: 0.9 },
          // The machine's image: the reflector at its APPARENT depth.
          { x: 0, depthCm: apparentCm, radiusCm: 0.16, halfWidthCm: 0.8, shape: 'box', echogenicity: 0.9, scatter: 0.2 },
        ],
      }
    }
    case 'sidelobe':
      return {
        ...base,
        targets: [
          { x: 0, depthCm: 4.2, radiusCm: 1.4, halfWidthCm: 1.9, echogenicity: 0.02, attenuation: 0.02, scatter: 0.1 },
          // Pseudo-debris: the machine's misplaced side-lobe echoes.
          { x: -0.12, depthCm: 3.6, radiusCm: 0.14, echogenicity: 0.22, attenuation: 0.02, scatter: 1 },
          { x: 0.08, depthCm: 4.3, radiusCm: 0.12, echogenicity: 0.18, attenuation: 0.02, scatter: 1 },
          { x: -0.04, depthCm: 4.9, radiusCm: 0.12, echogenicity: 0.15, attenuation: 0.02, scatter: 1 },
        ],
      }
    case 'gratinglobe':
      return {
        ...base,
        targets: [
          { x: -0.55, depthCm: 2.5, radiusCm: 0.3, echogenicity: 0.95, rim: 0.5, attenuation: 6, scatter: 0.4 },
          // The ghost the grating lobe painted on the other side of the image.
          { x: 0.45, depthCm: 2.5, radiusCm: 0.3, echogenicity: 0.35, scatter: 0.4 },
        ],
      }
    case 'beamwidth':
    case 'slicethickness':
      return {
        ...base,
        targets: [
          // A small deep cyst: with the focus set shallow, the wide beam smears
          // neighbouring speckle into it — the partial-volume fill is emergent.
          { x: 0, depthCm: 5.5, radiusCm: 0.45, echogenicity: 0.05, attenuation: 0.05, scatter: 0.2 },
          { x: -0.5, depthCm: 1.8, radiusCm: 0.4, echogenicity: 0.04, attenuation: 0.04, scatter: 0.15 },
        ],
      }
    case 'rangeambiguity':
      return {
        ...base,
        targets: [
          { x: -0.15, depthCm: 7.2, radiusCm: 0.35, echogenicity: 0.85, scatter: 0.4 },
          // The machine's mistake: the same reflector assigned to the next pulse.
          { x: -0.15, depthCm: 2.0, radiusCm: 0.35, echogenicity: 0.3, scatter: 0.4 },
        ],
      }
    case 'speckle':
      return { ...base, targets: [] }
    case 'anisotropy':
      return {
        ...base,
        targets: [
          // The tendon off-perpendicular: falsely dark despite being a strong reflector.
          { x: 0, depthCm: 3.2, radiusCm: 0.22, halfWidthCm: 1.9, shape: 'box', echogenicity: 0.16, scatter: 0.5 },
        ],
      }
    case 'twinkle':
      return {
        ...base,
        targets: [
          { x: 0, depthCm: 3.4, radiusCm: 0.3, echogenicity: 0.95, rim: 0.9, attenuation: 18, scatter: 0.9 },
        ],
      }
    default:
      // The Doppler set: an anechoic vessel crossing the field.
      return {
        ...base,
        targets: [
          { x: 0, depthCm: 3.9, radiusCm: 0.55, halfWidthCm: 2.5, shape: 'box', echogenicity: 0.03, attenuation: 0.05, scatter: 0.1 },
        ],
      }
  }
}

function equationFor(id: ArtefactId): string | undefined {
  switch (id) {
    case 'speed': {
      const apparent = apparentDepthMm(45, 1450) / 10
      return `apparent depth = true depth × 1540 / c_actual
              = 4.5 cm × 1540 / 1450 = ${apparent.toFixed(2)} cm   (too deep)`
    }
    case 'rangeambiguity': {
      const prf = maxPrfHz(80)
      return `max PRF = c / 2d = 1540 / (2 × 0.08 m) = ${prf.toFixed(0)} Hz
above this, echoes from 8 cm arrive after the next pulse`
    }
    case 'shadowing':
      return `loss through 0.7 cm of stone ≈ ${attenuationDb(20, 5, 0.7).toFixed(0)} dB (one way)
loss through 0.7 cm of tissue ≈ ${attenuationDb(0.5, 5, 0.7).toFixed(1)} dB`
    case 'enhancement':
      return `loss through 2 cm of fluid ≈ ${attenuationDb(0.02, 5, 2).toFixed(2)} dB
loss through 2 cm of tissue ≈ ${attenuationDb(0.5, 5, 2).toFixed(1)} dB — the difference IS the bright band`
    case 'reverberation':
      return `echo n arrives at n × Δt   →   drawn at n × d
equal time steps → equally spaced copies`
    case 'mirror':
      return `depth = c t / 2 — but t here includes the detour via the reflector,
so the copy is drawn beyond the mirror`
    case 'aliasing':
      return `Nyquist = PRF / 2 — shifts beyond it wrap to the opposite end of the scale`
    default:
      return undefined
  }
}

/* ------------------------------------------------------------------ *
 * The selector
 * ------------------------------------------------------------------ */

function ArtefactSelector({
  active,
  onPick,
}: {
  active: ArtefactId
  onPick: (id: ArtefactId) => void
}) {
  return (
    <div className="us-panel">
      <h3>
        <UsIcon name="ghost" size={13} />
        Artefact selector
      </h3>
      {GROUPS.map((group) => (
        <div key={group} style={{ marginBottom: 8 }}>
          <p className="us-slider-hint" style={{ margin: '4px 0' }}>
            <strong>{group}</strong>
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            {ARTEFACTS.filter((entry) => entry.group === group).map((entry) => (
              <button
                key={entry.id}
                type="button"
                className={entry.id === active ? 'us-chip is-on' : 'us-chip'}
                aria-pressed={entry.id === active}
                onClick={() => onPick(entry.id)}
                style={{ justifyContent: 'flex-start', width: '100%', borderRadius: 8, textAlign: 'left' }}
              >
                {entry.name}
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  )
}

/* ------------------------------------------------------------------ *
 * The page
 * ------------------------------------------------------------------ */

export default function ArtefactsPage() {
  const [state, setState] = useState<State>(DEFAULTS)
  const [showEquation, setShowEquation] = useState(true)
  const [showTrap, setShowTrap] = useState(true)
  const [revision, setRevision] = useState(false)
  const [detail, setDetail] = useState(false)
  const flash = useFlash()

  const patch = useCallback((next: Partial<State>) => setState((s) => ({ ...s, ...next })), [])
  const resetState = useCallback(() => {
    setState(DEFAULTS)
    flash.clear()
  }, [flash])

  const api = useGuided<State>({ steps: STEPS, setState: patch, resetState })
  const clock = useClock(api.playing, 60, api.index)

  const entry = ARTEFACT_BY_ID.get(state.artefactId) ?? ARTEFACTS[0]
  const phase = api.mode === 'manual' ? 'free' : (api.phase as ArtefactPhase)
  const sceneKind = phase === 'assumptions' ? 'assumptions' : entry.sceneKind

  const onPick = (id: ArtefactId) => {
    const next = ARTEFACT_BY_ID.get(id)
    if (!next) return
    patch({ artefactId: id })
    flash.fire([
      { text: next.name, dir: 'flat' },
      { text: `Violated: ${next.assumption.toLowerCase()}`, dir: 'warn' },
      { text: next.group === 'Doppler' ? 'Colour-box mock on the stage' : 'B-mode recomposed', dir: 'flat' },
    ])
  }

  const onReveal = (value: boolean) => {
    patch({ revealPath: value })
    flash.fire([
      { text: value ? 'Beam paths revealed' : 'Beam paths hidden', dir: 'flat' },
      { text: 'Amber = what the sound did', dir: value ? 'up' : 'flat' },
      { text: 'Dashed cyan = what the machine assumed', dir: value ? 'warn' : 'flat' },
    ])
  }

  const onFrequency = (value: number) => {
    const up = value > state.frequencyMHz
    patch({ frequencyMHz: value })
    flash.fire([
      { text: up ? 'Frequency increased' : 'Frequency decreased', dir: up ? 'up' : 'down' },
      { text: up ? 'Attenuation contrast rises' : 'Attenuation contrast falls', dir: up ? 'up' : 'down' },
      { text: up ? 'Shadows and enhancement strengthen' : 'Shadows and enhancement soften', dir: up ? 'warn' : 'flat' },
      { text: 'Refraction unchanged — it ignores frequency', dir: 'flat' },
    ])
  }

  const bmodeScene = useMemo(() => bmodeSceneFor(state.artefactId), [state.artefactId])
  const bmodeSettings: BModeSettings = useMemo(
    () => ({
      frequencyMHz: state.frequencyMHz,
      gainDb: 34,
      dynamicRangeDb: 55,
      // The beam-width and slice-thickness artefacts need the focus AWAY from
      // the lesion, so the partial-volume fill genuinely emerges from the blur.
      focusCm:
        state.artefactId === 'beamwidth' || state.artefactId === 'slicethickness' ? [1.8] : [3.5],
      apertureMm: state.artefactId === 'beamwidth' || state.artefactId === 'slicethickness' ? 8 : 12,
      cycles: 2,
      power: 1,
    }),
    [state.frequencyMHz, state.artefactId],
  )

  const equation = equationFor(state.artefactId)

  return (
    <UsLab
      path="/ultrasound-lab/artefacts"
      mode={api.mode}
      onModeChange={api.setMode}
      onReset={api.reset}
      focus={api.mode === 'guided' && !detail && !api.step.hands}
      stage={
        <>
          <section className="us-stage" aria-label="Artefact workshop">
            <div className="us-stage-head">
              <h2>
                <UsIcon name="ghost" size={14} />
                <b>Stage</b> {phase === 'assumptions' ? 'The four assumptions' : entry.name}
              </h2>
              <div className="us-legend">
                <span>
                  <i style={{ background: 'var(--us-amber)' }} /> True path
                </span>
                <span>
                  <i style={{ background: 'var(--us-cyan)' }} /> Assumed path
                </span>
                <span>
                  <i className="is-dot" style={{ background: 'var(--us-cyan)' }} /> Ghost (machine-placed)
                </span>
              </div>
            </div>

            <div className="us-stage-body">
              <div className="us-canvas-wrap">
                <StageFlash flash={flash} />
                <ArtefactStage
                  kind={sceneKind}
                  revealPath={state.revealPath}
                  time={clock}
                  phase={phase}
                  describe={
                    phase === 'assumptions'
                      ? 'The four machine assumptions: constant 1540 metres per second, straight-line travel, echoes from the main beam only, predictable attenuation.'
                      : `${entry.name}. ${entry.setup} ${entry.mechanism}`
                  }
                />
              </div>
              <div
                className="us-canvas-wrap"
                style={{ flex: '0 0 190px', maxWidth: 190, minWidth: 130 }}
              >
                <BMode
                  scene={bmodeScene}
                  settings={bmodeSettings}
                  label={phase === 'assumptions' ? 'B-mode' : entry.name}
                />
              </div>
            </div>

            <GuidedCaption api={api} state={state} />
            <GuidedTransport
              api={api}
              onShowEquation={() => setShowEquation((v) => !v)}
              onShowTrap={() => setShowTrap((v) => !v)}
              showingEquation={showEquation}
              showingTrap={showTrap}
              onToggleDetail={() => setDetail((v) => !v)}
              detailShown={detail}
            />
            <p className="us-focus-hint">
              One idea at a time. <b>Show the numbers</b> for the readouts and full analysis, or{' '}
              <b>Enter manual lab</b> to pick any artefact from the selector yourself.
            </p>
          </section>

          <FocusHide>
            <Readout
              items={[
                { label: 'Artefact', value: entry.name, tone: 'amber' },
                { label: 'Group', value: entry.group },
                { label: 'Violated assumption', value: entry.assumption, tone: 'cyan' },
                { label: 'Frequency', value: state.frequencyMHz.toFixed(1), unit: 'MHz' },
              ]}
            />
          </FocusHide>
        </>
      }
      controls={
        <>
          <ControlGroup title="Workshop controls" icon="sliders" defaultOpen>
            <Toggle
              label="Reveal beam path"
              checked={state.revealPath}
              onChange={onReveal}
              hint="Amber shows the path the sound actually took; dashed cyan shows the straight line the machine assumed."
            />
            <Slider
              label="Transmit frequency"
              unit="MHz"
              value={state.frequencyMHz}
              min={2}
              max={10}
              step={0.5}
              decimals={1}
              onChange={onFrequency}
              hint="Attenuation scales with frequency, so shadows and enhancement strengthen at high frequency. Refraction does not care."
            />
          </ControlGroup>

          <ArtefactSelector active={state.artefactId} onPick={onPick} />

          <div className="us-panel">
            <h3>
              <UsIcon name="lightbulb" size={13} />
              Check yourself
            </h3>
            <Predict
              question="A bright band appears deep to a rounded anechoic lesion. Mechanism?"
              options={[
                'Less energy was removed passing through the fluid',
                'The fluid focused the beam like a lens',
                'The machine applied extra gain to the lesion',
              ]}
              correct={0}
              explanation={
                <>
                  The beam that crossed the cyst was attenuated far <b>less</b> than its
                  neighbours, so the tissue beyond it returns stronger echoes — posterior
                  enhancement. It is the low-attenuation violation of the uniform-attenuation
                  assumption, and good evidence the lesion is truly fluid.
                </>
              }
            />
          </div>
        </>
      }
      teaching={
        <>
          <TeachingPanel
            revision={revision}
            onRevisionChange={setRevision}
            now={
              phase === 'assumptions' ? (
                <>
                  The scanner is building an image from four beliefs: <b>1540 m/s</b> everywhere,{' '}
                  <b>straight-line</b> travel, echoes from the <b>main beam</b> only, and{' '}
                  <b>predictable attenuation</b>. While all four hold, the image is faithful.
                </>
              ) : (
                <>
                  <b>{entry.name}.</b> {entry.setup}
                </>
              )
            }
            why={
              phase === 'assumptions' ? (
                <>
                  Every artefact in this workshop is one of the four assumptions being violated.
                  Name the violated assumption and you have named the artefact family — that is how
                  the recall questions are built.
                </>
              ) : (
                <>{entry.mechanism}</>
              )
            }
            equation={showEquation ? equation : undefined}
            deltas={
              phase === 'assumptions'
                ? [
                    { label: 'speed wrong → axial displacement', dir: 'warn' },
                    { label: 'path bent → lateral misplacement', dir: 'warn' },
                    { label: 'off-axis echo → pseudo-debris', dir: 'warn' },
                    { label: 'attenuation odd → shadow / enhancement', dir: 'warn' },
                  ]
                : entry.deltas
            }
            clinical={
              phase === 'assumptions' ? (
                <>
                  Artefacts are not noise: shadowing confirms a stone, enhancement confirms a cyst,
                  twinkle finds calculi. Reading them is a clinical skill, not housekeeping.
                </>
              ) : (
                <>
                  <b>Recognise:</b> {entry.recognition} <b>Respond:</b> {entry.fix}
                </>
              )
            }
            trap={showTrap ? <>{entry.trap}</> : undefined}
          />

          <MoreDetail title="More detail — the artefact families and their assumptions">
            <p>
              <strong>Attenuation family.</strong> Shadowing and enhancement are the same failure
              in opposite directions: the tissue removed more, or less, energy than the machine
              compensated for. Both emerge in the B-mode panel here from the attenuation model
              alone — nothing is painted on.
            </p>
            <p>
              <strong>Path family.</strong> Reverberation, comet-tail, mirror image and refraction
              all break the straight-line, single-trip assumption. The machine converts every
              microsecond of delay into millimetres of depth along the assumed line, so a detour
              becomes a ghost. Ring-down sits beside them but is a <em>resonant emission</em> from
              trapped fluid, not a chain of reflections.
            </p>
            <p>
              <strong>Geometry family.</strong> Side lobes, grating lobes, beam width and slice
              thickness all violate “echoes come from the main, infinitely thin beam”. Anisotropy
              (met properly in <Link to="/ultrasound-lab/reflection">Reflection</Link>) is the
              angle-dependence of specular reflectors masquerading as pathology.
            </p>
            <p>
              <strong>Timing and sampling family.</strong> Range ambiguity is PRF pushed beyond
              c/2d. Colour and spectral aliasing (built interactively in{' '}
              <Link to="/ultrasound-lab/aliasing">PRF, Nyquist &amp; Aliasing</Link>) are the same
              sampling failure applied to Doppler shifts.
            </p>
            <p>
              <strong>Speckle</strong> is the odd one out: it is present in every image, it is the
              interference pattern of sub-wavelength scatterers, and no machine setting removes it
              — compounding merely averages independent patterns.
            </p>

            <TrapNote>
              The single most repeated artefact trap in the collection: “acoustic shadowing can be
              caused by both cysts and gallstones” is <b>FALSE</b> (QBank Q382). A cyst produces{' '}
              <em>posterior enhancement</em>. If a stem pairs cysts with shadowing, it is wrong.
            </TrapNote>

            <SourceNote>
              QBank Q412 separates <b>comet-tail</b> (true reverberation between closely spaced
              interfaces) from <b>ring-down</b> (continuous resonant emission from fluid trapped
              between gas bubbles). Many revision cards blur the two; the question bank marks the
              blurred version false, and this workshop draws them as physically different events.
            </SourceNote>
          </MoreDetail>

          <ModelNote>
            The B-mode panel computes shadowing, enhancement and partial-volume fill from the
            physics. Beam-path ghosts — reverberation copies, the mirror duplicate, side-lobe
            debris — are placed as explicit targets, because they are exactly that: echoes the
            machine placed at the wrong coordinates. The scenes are schematic in scale; the
            relationships and directions are faithful.
          </ModelNote>
        </>
      }
    />
  )
}
