#!/usr/bin/env node
/* ===========================================================================
   The anatomy summary — the few facts the home page needs, without the bank.

       npm run anatomy:summary

   WHY THIS EXISTS. src/anatomy/pages/Home.tsx imported getSectionQuestions,
   which pulls the whole question dataset: every label, marker coordinate,
   accepted variant and teaching paragraph for 510 questions. Built, that is a
   ONE MEGABYTE javascript chunk, and the anatomy home was downloading and
   parsing all of it to display six region cards.

   What the home actually uses from it is small enough to be embarrassing:

     - how many questions each region has          (a number)
     - the sum of its answer counts, for maxScore  (a number)
     - the distinct imaging modalities it contains (a few strings)
     - the list of question ids, to open one at random

   Everything else on that page — attempted, score, percentage — already comes
   from the learner's progress store, not from the bank.

   So this script precomputes exactly those facts into a file a few kilobytes
   wide. The bank is still THE source of truth and is still loaded in full the
   moment a learner opens a section or answers a question; it is simply no
   longer the price of admission to the front page.

   KEPT HONEST BY A TEST. summary.test.ts regenerates these numbers from the
   real data and fails if they disagree, so a summary that drifts after an
   edit to the bank is a red build rather than a wrong number on the home page.
   =========================================================================== */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'src', 'anatomy', 'data');

/* The same six files, under the same ids, that data/sections.ts resolves. */
const FILES = {
  'head-neck': 'headNeck.json',
  spine: 'spine.json',
  thorax: 'thorax.json',
  'abdo-pelvis': 'abdoPelvis.json',
  'upper-limb': 'upperLimb.json',
  'lower-limb': 'lowerLimb.json',
};

const summary = {};
let questions = 0;
let answers = 0;

for (const [section, file] of Object.entries(FILES)) {
  const rows = JSON.parse(readFileSync(join(dataDir, file), 'utf8'));
  /* excludeFromPlay questions are held in the bank but never served, and the
     home's counts must match what a learner can actually reach. */
  const playable = rows.filter((q) => !q.excludeFromPlay);

  const modalities = [...new Set(playable.map((q) => q.imagingModality).filter(Boolean))].sort();
  /* id and answer-count only. The count is what maxScore is built from —
     two marks per label — and the id is what "open one at random" needs. */
  const items = playable.map((q) => [q.id, Object.keys(q.answers ?? {}).length]);

  summary[section] = { modalities, questions: items };
  questions += items.length;
  answers += items.reduce((n, [, c]) => n + c, 0);
}

const out = `/* GENERATED by scripts/anatomy-summary.mjs — do not edit by hand.
 *
 * The handful of facts the anatomy home needs, so that page never has to
 * import the question bank. Regenerate with:  npm run anatomy:summary
 * Kept in step with the bank by src/anatomy/data/summary.test.ts.
 */

export type SectionSummary = {
  /** Distinct imaging modalities present in the region. */
  modalities: string[];
  /** [question id, number of answers] for every playable question. */
  questions: [string, number][];
};

export const ANATOMY_SUMMARY: Record<string, SectionSummary> = ${JSON.stringify(summary, null, 2)};
`;

writeFileSync(join(dataDir, 'summary.ts'), out);

const bytes = Buffer.byteLength(out);
console.log(`\nAnatomy summary written.`);
console.log(`  ${questions} playable questions, ${answers} answers, 6 regions`);
console.log(`  ${(bytes / 1024).toFixed(1)} KB  src/anatomy/data/summary.ts\n`);
