/**
 * Question -> section, one checked-in row per bank question.
 *
 * GENERATED ONCE by scripts/physics-map-bootstrap.ts, then edited by hand.
 * Do not regenerate: it would discard every hand review below.
 *
 * WHY A FILE INSTEAD OF A RESOLVER. Assignment used to be computed at runtime
 * from three ordered guesses — visualTags intersection, then a keyword regex
 * over the stem text, then "whichever section the topic declared first". The
 * first two are reasonable heuristics. The third is not a decision at all, and
 * 47 questions were being resolved by it. Worse, none of the three recorded
 * WHY, so a question in the wrong section looked exactly like a question in
 * the right one, and 117 questions where the tag and the keyword
 * actively disagreed were resolved silently in favour of the tag.
 *
 * Every row now says how it was decided:
 *
 *   'tag'      the recall annotation claimed it. Usually right; unreviewed.
 *   'kw'       a section keyword matched the text. Plausible; unreviewed.
 *   'manual'   a person decided. Requires a note saying what they saw.
 *
 * 'tag' and 'kw' are review debt, reported by `npm run physics:map` as W1 and
 * meant to trend to zero. There is no 'fallback' provenance and no fallback in
 * the app: an unmapped question renders as unassigned and is reported, rather
 * than being quietly filed somewhere wrong.
 */

export type QuestionMapEntry = {
  /** Bank question id. */
  q: string
  /** Syllabus topic id. */
  topic: string
  /** Section id within that topic. */
  section: string
  /** Concept id on that topic, for the principle shown under a wrong answer. */
  concept?: string
  /** How this row was decided. */
  by: 'manual' | 'tag' | 'kw'
  /** Set when this row deliberately contradicts the bank's own q.topic. */
  overrideTopic?: true
  /** REQUIRED when by:'manual' or overrideTopic. What the reviewer saw. */
  note?: string
}

export const QUESTION_MAP: QuestionMapEntry[] = [
  { q: 'b1', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b2', topic: 'xray', section: 'spectrum', concept: 'characteristic', by: 'kw' },
  { q: 'b3', topic: 'xray', section: 'foundations', concept: 'isotopes-isobars', by: 'manual', note: 'A bootstrap fallback that landed in quality because nothing matched. It is about atomic structure — proton number, mass number, half-life — which is what foundations teaches.' },
  { q: 'b4', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b46', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b48', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b93', topic: 'xray', section: 'spectrum', concept: 'filtration', by: 'tag' },
  { q: 'b97', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b129', topic: 'xray', section: 'interactions', concept: 'attenuation', by: 'tag' },
  { q: 'b136', topic: 'xray', section: 'geometry', concept: 'focal-spot', by: 'kw' },
  { q: 'b138', topic: 'xray', section: 'geometry', by: 'kw' },
  { q: 'b165', topic: 'xray', section: 'geometry', concept: 'focal-spot', by: 'tag' },
  { q: 'b167', topic: 'xray', section: 'interactions', by: 'kw' },
  { q: 'b169', topic: 'xray', section: 'quality', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b179', topic: 'xray', section: 'spectrum', concept: 'filtration', by: 'tag' },
  { q: 'b180', topic: 'xray', section: 'tube', by: 'kw' },
  { q: 'b181', topic: 'xray', section: 'quality', by: 'kw' },
  { q: 'b205', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b209', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'kw' },
  { q: 'b215', topic: 'xray', section: 'tube', concept: 'focal-spot', by: 'tag' },
  { q: 'b216', topic: 'xray', section: 'quality', by: 'kw' },
  { q: 'b225', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b237', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b240', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b249', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b250', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b252', topic: 'xray', section: 'quality', by: 'kw' },
  { q: 'b253', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b265', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b266', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b270', topic: 'xray', section: 'interactions', by: 'tag' },
  { q: 'b280', topic: 'xray', section: 'quality', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b281', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b282', topic: 'xray', section: 'tube', concept: 'focal-spot', by: 'tag' },
  { q: 'b283', topic: 'xray', section: 'geometry', concept: 'focal-spot', by: 'tag' },
  { q: 'b294', topic: 'xray', section: 'foundations', concept: 'characteristic', by: 'kw' },
  { q: 'b295', topic: 'xray', section: 'interactions', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b296', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b297', topic: 'xray', section: 'tube', concept: 'focal-spot', by: 'tag' },
  { q: 'b298', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b324', topic: 'xray', section: 'interactions', by: 'tag' },
  { q: 'b325', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b326', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b327', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b328', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b354', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b355', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b356', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b360', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b384', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b385', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b386', topic: 'xray', section: 'interactions', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b387', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b388', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b414', topic: 'xray', section: 'filtration', concept: 'filtration', by: 'kw' },
  { q: 'b415', topic: 'xray', section: 'spectrum', concept: 'kvp-vs-mas', by: 'tag' },
  { q: 'b417', topic: 'xray', section: 'spectrum', by: 'tag' },
  { q: 'b418', topic: 'xray', section: 'foundations', concept: 'filtration', by: 'kw' },
  { q: 'b420', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b429', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b431', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'tag' },
  { q: 'b435', topic: 'xray', section: 'foundations', by: 'kw' },
  { q: 'b436', topic: 'xray', section: 'foundations', concept: 'attenuation', by: 'tag' },
  { q: 'b442', topic: 'xray', section: 'interactions', concept: 'characteristic', by: 'tag' },
  { q: 'b444', topic: 'xray', section: 'interactions', concept: 'pe-vs-compton', by: 'kw' },
  { q: 'b453', topic: 'xray', section: 'geometry', concept: 'focal-spot', by: 'tag' },
  { q: 'x46', topic: 'xray', section: 'tube', concept: 'kvp-vs-mas', by: 'kw' },
  { q: 'x52', topic: 'xray', section: 'foundations', concept: 'kvp-vs-mas', by: 'kw' },
  { q: 'x53', topic: 'xray', section: 'tube', concept: 'kvp-vs-mas', by: 'kw' },
  { q: 'x57', topic: 'xray', section: 'tube', concept: 'kvp-vs-mas', by: 'kw' },
  { q: 'b6', topic: 'digital', section: 'latitude', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b9', topic: 'digital', section: 'cr', concept: 'indirect-direct', by: 'kw' },
  { q: 'b82', topic: 'digital', section: 'latitude', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b99', topic: 'digital', section: 'cr', concept: 'indirect-direct', by: 'kw' },
  { q: 'b100', topic: 'digital', section: 'sampling', concept: 'pixel-arithmetic', by: 'kw' },
  { q: 'b101', topic: 'digital', section: 'cr', by: 'kw' },
  { q: 'b183', topic: 'digital', section: 'cr', by: 'kw' },
  { q: 'b226', topic: 'digital', section: 'cr', by: 'kw' },
  { q: 'b236', topic: 'digital', section: 'sampling', concept: 'pixel-arithmetic', by: 'kw' },
  { q: 'b242', topic: 'digital', section: 'sampling', concept: 'pixel-arithmetic', by: 'kw' },
  { q: 'b256', topic: 'digital', section: 'quality', concept: 'mtf', by: 'manual', note: 'Every stem is MTF: that it measures spatial resolution, that direct DR beats film/screen, that scatter and motion degrade it. It landed on panels only because panels is declared first.' },
  { q: 'b267', topic: 'digital', section: 'cr', concept: 'cr-readout', by: 'kw' },
  { q: 'b273', topic: 'digital', section: 'panels', concept: 'indirect-direct', by: 'kw' },
  { q: 'b299', topic: 'digital', section: 'cr', concept: 'cr-readout', by: 'kw' },
  { q: 'b329', topic: 'digital', section: 'sampling', concept: 'pixel-arithmetic', by: 'kw' },
  { q: 'b357', topic: 'digital', section: 'sampling', concept: 'pixel-arithmetic', by: 'kw' },
  { q: 'b389', topic: 'digital', section: 'cr', concept: 'cr-readout', by: 'kw' },
  { q: 'b424', topic: 'digital', section: 'cr', concept: 'cr-fading', by: 'kw' },
  { q: 'b7', topic: 'fluoro', section: 'intensifier', concept: 'ii-chain', by: 'tag' },
  { q: 'b8', topic: 'fluoro', section: 'dsa', concept: 'dsa-snr', by: 'tag' },
  { q: 'b130', topic: 'fluoro', section: 'dsa', concept: 'dsa-snr', by: 'tag' },
  { q: 'b187', topic: 'fluoro', section: 'distortion', by: 'manual', note: 'Periphery brighter than centre is vignetting, an electron-optic distortion. It reached dose only as the topic fallback.' },
  { q: 'b218', topic: 'fluoro', section: 'dsa', concept: 'dsa-snr', by: 'tag' },
  { q: 'b227', topic: 'fluoro', section: 'intensifier', concept: 'ii-distortion', by: 'tag' },
  { q: 'b257', topic: 'fluoro', section: 'intensifier', concept: 'ii-chain', by: 'kw' },
  { q: 'b259', topic: 'fluoro', section: 'dsa', concept: 'dsa-snr', by: 'tag' },
  { q: 'b275', topic: 'fluoro', section: 'dose', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b279', topic: 'fluoro', section: 'intensifier', by: 'tag' },
  { q: 'b300', topic: 'fluoro', section: 'intensifier', concept: 'brightness-gain', by: 'tag' },
  { q: 'b330', topic: 'fluoro', section: 'dsa', concept: 'dsa-snr', by: 'tag' },
  { q: 'b358', topic: 'fluoro', section: 'distortion', by: 'kw' },
  { q: 'b359', topic: 'fluoro', section: 'abc', concept: 'abc', by: 'kw' },
  { q: 'b390', topic: 'fluoro', section: 'intensifier', concept: 'brightness-gain', by: 'tag' },
  { q: 'b427', topic: 'fluoro', section: 'intensifier', concept: 'skin-dose', by: 'tag' },
  { q: 'b448', topic: 'fluoro', section: 'dsa', concept: 'skin-dose', by: 'tag' },
  { q: 'b5', topic: 'mammo', section: 'compression', concept: 'compression-wins', by: 'tag' },
  { q: 'b139', topic: 'mammo', section: 'tomo', concept: 'tomo', by: 'tag' },
  { q: 'b140', topic: 'mammo', section: 'quality', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b255', topic: 'mammo', section: 'compression', concept: 'compression-wins', by: 'tag' },
  { q: 'b268', topic: 'mammo', section: 'spectrum', concept: 'mammo-energy', by: 'manual', note: 'Mo-Mo target/filter and 20-24 keV characteristic radiation carry the question; the focal spot and dose stems are incidental.' },
  { q: 'b269', topic: 'mammo', section: 'compression', by: 'tag' },
  { q: 'b331', topic: 'mammo', section: 'energy', concept: 'target-filter', by: 'manual', note: '25-35 kVp, and the trap that characteristic x-rays must NOT be filtered out, are both the low-energy choice; the focal spot and SID stems are incidental.' },
  { q: 'b391', topic: 'mammo', section: 'compression', concept: 'compression-wins', by: 'tag' },
  { q: 'b432', topic: 'mammo', section: 'geometry', concept: 'mag-air-gap', by: 'manual', note: 'Distortion, geometric unsharpness, object-detector distance and magnification: the geometry section outright.' },
  { q: 'b439', topic: 'mammo', section: 'compression', by: 'tag' },
  { q: 'b10', topic: 'ct', section: 'hu-window', concept: 'pitch', by: 'tag' },
  { q: 'b11', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b12', topic: 'ct', section: 'noise-quality', by: 'kw' },
  { q: 'b13', topic: 'ct', section: 'hu-window', concept: 'windowing', by: 'tag' },
  { q: 'b37', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b45', topic: 'ct', section: 'hu-window', concept: 'windowing', by: 'tag' },
  { q: 'b52', topic: 'ct', section: 'hu-window', concept: 'hounsfield', by: 'kw' },
  { q: 'b53', topic: 'ct', section: 'artefacts', concept: 'beam-hardening', by: 'tag' },
  { q: 'b54', topic: 'ct', section: 'acquisition', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b61', topic: 'ct', section: 'acquisition', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b83', topic: 'ct', section: 'helical', by: 'kw' },
  { q: 'b127', topic: 'ct', section: 'dose', by: 'kw' },
  { q: 'b133', topic: 'ct', section: 'acquisition', concept: 'reconstruction', by: 'kw' },
  { q: 'b149', topic: 'ct', section: 'acquisition', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b166', topic: 'ct', section: 'acquisition', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b184', topic: 'ct', section: 'acquisition', concept: 'hounsfield', by: 'kw' },
  { q: 'b185', topic: 'ct', section: 'hu-window', concept: 'hounsfield', by: 'tag' },
  { q: 'b186', topic: 'ct', section: 'hu-window', concept: 'hounsfield', by: 'kw' },
  { q: 'b228', topic: 'ct', section: 'artefacts', concept: 'hounsfield', by: 'tag' },
  { q: 'b229', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b231', topic: 'ct', section: 'acquisition', concept: 'reconstruction', by: 'kw' },
  { q: 'b232', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b241', topic: 'ct', section: 'hu-window', concept: 'windowing', by: 'tag' },
  { q: 'b245', topic: 'ct', section: 'helical', concept: 'pitch', by: 'kw' },
  { q: 'b272', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b284', topic: 'ct', section: 'hu-window', concept: 'hounsfield', by: 'kw' },
  { q: 'b310', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b311', topic: 'ct', section: 'noise-quality', by: 'kw' },
  { q: 'b312', topic: 'ct', section: 'hu-window', concept: 'windowing', by: 'tag' },
  { q: 'b313', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b314', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b341', topic: 'ct', section: 'acquisition', concept: 'beam-hardening', by: 'kw' },
  { q: 'b342', topic: 'ct', section: 'hu-window', concept: 'pitch', by: 'tag' },
  { q: 'b343', topic: 'ct', section: 'dose', concept: 'dose-chain', by: 'tag' },
  { q: 'b344', topic: 'ct', section: 'helical', concept: 'pitch', by: 'kw' },
  { q: 'b370', topic: 'ct', section: 'acquisition', concept: 'reconstruction', by: 'kw' },
  { q: 'b371', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b372', topic: 'ct', section: 'artefacts', concept: 'noise-sqrt', by: 'tag' },
  { q: 'b373', topic: 'ct', section: 'acquisition', by: 'kw' },
  { q: 'b374', topic: 'ct', section: 'artefacts', concept: 'beam-hardening', by: 'tag' },
  { q: 'b401', topic: 'ct', section: 'helical', concept: 'pitch', by: 'tag' },
  { q: 'b402', topic: 'ct', section: 'acquisition', concept: 'noise-sqrt', by: 'kw' },
  { q: 'b403', topic: 'ct', section: 'acquisition', concept: 'pitch', by: 'kw' },
  { q: 'b404', topic: 'ct', section: 'dose', concept: 'dose-chain', by: 'tag' },
  { q: 'b425', topic: 'ct', section: 'hu-window', concept: 'hounsfield', by: 'tag' },
  { q: 'b430', topic: 'ct', section: 'hu-window', concept: 'hounsfield', by: 'tag' },
  { q: 'b445', topic: 'ct', section: 'noise-quality', concept: 'noise-sqrt', by: 'kw' },
  { q: 'b447', topic: 'ct', section: 'artefacts', concept: 'beam-hardening', by: 'tag' },
  { q: 'x41', topic: 'ct', section: 'acquisition', concept: 'reconstruction', by: 'kw' },
  { q: 'x42', topic: 'ct', section: 'helical', concept: 'pitch', by: 'kw' },
  { q: 'x43', topic: 'ct', section: 'acquisition', concept: 'noise-sqrt', by: 'kw' },
  { q: 'b15', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b16', topic: 'nm', section: 'pet', by: 'tag' },
  { q: 'b17', topic: 'nm', section: 'tracer', concept: 'ideal-tracer', by: 'kw' },
  { q: 'b18', topic: 'nm', section: 'quant', concept: 'suv', by: 'tag' },
  { q: 'b19', topic: 'nm', section: 'quant', concept: 'suv', by: 'tag' },
  { q: 'b20', topic: 'nm', section: 'camera', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b25', topic: 'nm', section: 'acquisition', concept: 'spect', by: 'tag' },
  { q: 'b26', topic: 'nm', section: 'acquisition', concept: 'spect', by: 'tag' },
  { q: 'b35', topic: 'safety', section: 'staff', by: 'manual', overrideTopic: true, note: 'Stems A and B are staff protection during radionuclide imaging (aprons, lead thickness). The title and the two ultrasound stems are recall artefacts of a garbled source question.' },
  { q: 'b62', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b64', topic: 'nm', section: 'camera', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b65', topic: 'nm', section: 'pet', concept: 'crystal', by: 'tag' },
  { q: 'b72', topic: 'nm', section: 'pet', by: 'kw' },
  { q: 'b76', topic: 'nm', section: 'camera', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b152', topic: 'nm', section: 'tracer', by: 'kw' },
  { q: 'b168', topic: 'nm', section: 'camera', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b191', topic: 'nm', section: 'performance', concept: 'collimator-trade', by: 'manual', note: 'Whether 3 mm objects resolve is system resolution, paired with what the collimator is actually for.' },
  { q: 'b192', topic: 'nm', section: 'acquisition', concept: 'spect', by: 'tag' },
  { q: 'b193', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b194', topic: 'nm', section: 'tracer', by: 'kw' },
  { q: 'b220', topic: 'nm', section: 'pet', concept: 'pet-coincidence', by: 'tag' },
  { q: 'b221', topic: 'nm', section: 'performance', concept: 'generator', by: 'manual', note: 'High-sensitivity versus high-resolution collimator IS the resolution/sensitivity trade this section teaches.' },
  { q: 'b222', topic: 'nm', section: 'tracer', concept: 'tc99m', by: 'kw' },
  { q: 'b247', topic: 'nm', section: 'tracer', concept: 'generator', by: 'kw' },
  { q: 'b261', topic: 'nm', section: 'tracer', concept: 'tc99m', by: 'kw' },
  { q: 'b262', topic: 'nm', section: 'tracer', concept: 'generator', by: 'kw' },
  { q: 'b263', topic: 'nm', section: 'tracer', concept: 'generator', by: 'kw' },
  { q: 'b278', topic: 'nm', section: 'camera', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b285', topic: 'nm', section: 'tracer', by: 'kw' },
  { q: 'b286', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b301', topic: 'nm', section: 'tracer', concept: 'tc99m', by: 'kw' },
  { q: 'b302', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b303', topic: 'nm', section: 'performance', concept: 'collimator-trade', by: 'manual', note: 'Resolution deteriorating with collimator distance, and 10 mm FWHM as the number to know.' },
  { q: 'b304', topic: 'nm', section: 'acquisition', concept: 'tc99m', by: 'tag' },
  { q: 'b305', topic: 'nm', section: 'acquisition', concept: 'crystal', by: 'tag' },
  { q: 'b309', topic: 'nm', section: 'tracer', by: 'kw' },
  { q: 'b332', topic: 'nm', section: 'tracer', concept: 'generator', by: 'kw' },
  { q: 'b333', topic: 'nm', section: 'camera', concept: 'tc99m', by: 'tag' },
  { q: 'b334', topic: 'nm', section: 'acquisition', concept: 'spect', by: 'tag' },
  { q: 'b335', topic: 'nm', section: 'pet', concept: 'pet-coincidence', by: 'tag' },
  { q: 'b338', topic: 'nm', section: 'tracer', concept: 'tc99m', by: 'kw' },
  { q: 'b361', topic: 'nm', section: 'tracer', concept: 'tc99m', by: 'kw' },
  { q: 'b362', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b363', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b364', topic: 'nm', section: 'pet', concept: 'pet-coincidence', by: 'tag' },
  { q: 'b365', topic: 'nm', section: 'quant', concept: 'suv', by: 'tag' },
  { q: 'b392', topic: 'nm', section: 'tracer', by: 'kw' },
  { q: 'b393', topic: 'nm', section: 'performance', concept: 'tc99m', by: 'manual', note: 'Crystal thickness against resolution, septal penetration above 200 keV, and under 0.1 per cent of emitted gammas used: the collimator bill, itemised.' },
  { q: 'b394', topic: 'nm', section: 'acquisition', concept: 'spect', by: 'tag' },
  { q: 'b395', topic: 'nm', section: 'pet', concept: 'pet-coincidence', by: 'tag' },
  { q: 'b399', topic: 'nm', section: 'quant', concept: 'dose-committed', by: 'kw' },
  { q: 'b400', topic: 'nm', section: 'tracer', concept: 'tc99m', by: 'kw' },
  { q: 'b416', topic: 'nm', section: 'quant', by: 'kw' },
  { q: 'b441', topic: 'nm', section: 'camera', concept: 'collimator-trade', by: 'tag' },
  { q: 'b443', topic: 'safety', section: 'legislation', by: 'manual', overrideTopic: true, note: 'Every stem is DRLs under IR(ME)R: set nationally, audited by the employer. Filed under Nuclear Medicine in the bank because stem C mentions administered activity.' },
  { q: 'b451', topic: 'nm', section: 'camera', concept: 'generator', by: 'tag' },
  { q: 'x47', topic: 'nm', section: 'tracer', by: 'kw' },
  { q: 'x49', topic: 'nm', section: 'tracer', concept: 'dose-committed', by: 'kw' },
  { q: 'b14', topic: 'mri', section: 'safety', concept: 'static-field', by: 'kw' },
  { q: 'b22', topic: 'mri', section: 'signal', concept: 'kspace-centre', by: 'tag' },
  { q: 'b23', topic: 'mri', section: 'relaxation', concept: 'weighting', by: 'tag' },
  { q: 'b24', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b27', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b38', topic: 'mri', section: 'encoding', concept: 'kspace-centre', by: 'tag' },
  { q: 'b43', topic: 'mri', section: 'safety', by: 'kw' },
  { q: 'b73', topic: 'mri', section: 'safety', by: 'kw' },
  { q: 'b74', topic: 'mri', section: 'safety', by: 'kw' },
  { q: 'b75', topic: 'mri', section: 'sequences', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b81', topic: 'mri', section: 'signal', concept: 'sar', by: 'tag' },
  { q: 'b107', topic: 'mri', section: 'signal', concept: 'larmor', by: 'tag' },
  { q: 'b108', topic: 'mri', section: 'quality', concept: 'artefact-axes', by: 'kw' },
  { q: 'b113', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b121', topic: 'mri', section: 'sequences', concept: 'spin-echo-t2star', by: 'kw' },
  { q: 'b123', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'kw' },
  { q: 'b150', topic: 'mri', section: 'weighting', by: 'kw' },
  { q: 'b159', topic: 'mri', section: 'sequences', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b161', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'kw' },
  { q: 'b164', topic: 'mri', section: 'weighting', concept: 'snr-trades', by: 'tag' },
  { q: 'b197', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b198', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'tag' },
  { q: 'b199', topic: 'mri', section: 'sequences', concept: 'ir-null', by: 'kw' },
  { q: 'b200', topic: 'mri', section: 'sequences', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b201', topic: 'mri', section: 'safety', by: 'kw' },
  { q: 'b202', topic: 'mri', section: 'signal', concept: 'sar', by: 'tag' },
  { q: 'b207', topic: 'mri', section: 'safety', by: 'kw' },
  { q: 'b208', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b217', topic: 'mri', section: 'weighting', concept: 'snr-trades', by: 'tag' },
  { q: 'b233', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'tag' },
  { q: 'b234', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b244', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b246', topic: 'mri', section: 'relaxation', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b264', topic: 'mri', section: 'quality', concept: 'artefact-axes', by: 'tag' },
  { q: 'b290', topic: 'mri', section: 'safety', concept: 'static-field', by: 'kw' },
  { q: 'b291', topic: 'mri', section: 'safety', concept: 'sar', by: 'tag' },
  { q: 'b292', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b293', topic: 'mri', section: 'quality', concept: 'kspace-centre', by: 'tag' },
  { q: 'b315', topic: 'mri', section: 'signal', concept: 'larmor', by: 'tag' },
  { q: 'b316', topic: 'mri', section: 'signal', concept: 'larmor', by: 'tag' },
  { q: 'b317', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b318', topic: 'mri', section: 'signal', concept: 'weighting', by: 'tag' },
  { q: 'b345', topic: 'mri', section: 'signal', by: 'tag' },
  { q: 'b346', topic: 'mri', section: 'relaxation', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b347', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'kw' },
  { q: 'b348', topic: 'mri', section: 'quality', concept: 'ir-null', by: 'tag' },
  { q: 'b349', topic: 'mri', section: 'signal', concept: 'sar', by: 'tag' },
  { q: 'b375', topic: 'mri', section: 'signal', concept: 'larmor', by: 'tag' },
  { q: 'b376', topic: 'mri', section: 'signal', concept: 'kspace-centre', by: 'tag' },
  { q: 'b377', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'tag' },
  { q: 'b378', topic: 'mri', section: 'safety', concept: 'static-field', by: 'kw' },
  { q: 'b405', topic: 'mri', section: 'signal', concept: 't1-vs-t2', by: 'tag' },
  { q: 'b406', topic: 'mri', section: 'signal', concept: 'larmor', by: 'kw' },
  { q: 'b407', topic: 'mri', section: 'quality', concept: 'weighting', by: 'tag' },
  { q: 'b408', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b409', topic: 'mri', section: 'weighting', concept: 'static-field', by: 'kw' },
  { q: 'b419', topic: 'mri', section: 'weighting', concept: 'weighting', by: 'tag' },
  { q: 'b426', topic: 'mri', section: 'signal', concept: 'larmor', by: 'tag' },
  { q: 'b438', topic: 'mri', section: 'relaxation', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b440', topic: 'mri', section: 'signal', concept: 'ir-null', by: 'tag' },
  { q: 'b450', topic: 'mri', section: 'signal', concept: 'spin-echo-t2star', by: 'tag' },
  { q: 'b21', topic: 'us', section: 'safety', concept: 'mi-vs-ti', by: 'tag' },
  { q: 'b31', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b32', topic: 'us', section: 'safety', concept: 'mi-vs-ti', by: 'kw' },
  { q: 'b33', topic: 'us', section: 'waves', concept: 'speed-medium', by: 'kw' },
  { q: 'b34', topic: 'us', section: 'doppler', by: 'tag' },
  { q: 'b84', topic: 'us', section: 'artefacts', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b85', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b86', topic: 'us', section: 'artefacts', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b89', topic: 'us', section: 'safety', concept: 'mi-vs-ti', by: 'tag' },
  { q: 'b112', topic: 'us', section: 'doppler', by: 'tag' },
  { q: 'b117', topic: 'us', section: 'transducer', by: 'kw' },
  { q: 'b119', topic: 'us', section: 'doppler', concept: 'nyquist', by: 'kw' },
  { q: 'b120', topic: 'us', section: 'artefacts', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b135', topic: 'us', section: 'artefacts', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b151', topic: 'us', section: 'attenuation', concept: 'attenuation-rule', by: 'kw' },
  { q: 'b177', topic: 'us', section: 'transducer', concept: 'thickness-frequency', by: 'kw' },
  { q: 'b195', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b196', topic: 'us', section: 'doppler', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b203', topic: 'us', section: 'waves', by: 'kw' },
  { q: 'b206', topic: 'us', section: 'safety', concept: 'mi-vs-ti', by: 'kw' },
  { q: 'b210', topic: 'us', section: 'doppler', concept: 'nyquist', by: 'tag' },
  { q: 'b211', topic: 'us', section: 'doppler', concept: 'speed-medium', by: 'tag' },
  { q: 'b212', topic: 'us', section: 'artefacts', by: 'kw', note: 'BOOTSTRAP FALLBACK — nothing matched; needs a human' },
  { q: 'b219', topic: 'us', section: 'attenuation', concept: 'gain-vs-power', by: 'kw' },
  { q: 'b235', topic: 'us', section: 'doppler', concept: 'mi-vs-ti', by: 'tag' },
  { q: 'b238', topic: 'us', section: 'waves', concept: 'speed-medium', by: 'kw' },
  { q: 'b239', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b287', topic: 'us', section: 'safety', concept: 'attenuation-rule', by: 'tag' },
  { q: 'b288', topic: 'us', section: 'attenuation', concept: 'gain-vs-power', by: 'kw' },
  { q: 'b289', topic: 'us', section: 'transducer', concept: 'nyquist', by: 'kw' },
  { q: 'b319', topic: 'us', section: 'waves', concept: 'speed-medium', by: 'tag' },
  { q: 'b320', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b321', topic: 'us', section: 'transducer', concept: 'resolution-owners', by: 'kw' },
  { q: 'b322', topic: 'us', section: 'doppler', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b323', topic: 'us', section: 'doppler', concept: 'mi-vs-ti', by: 'tag' },
  { q: 'b350', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b351', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b352', topic: 'us', section: 'transducer', concept: 'resolution-owners', by: 'kw' },
  { q: 'b353', topic: 'us', section: 'doppler', concept: 'speed-medium', by: 'tag' },
  { q: 'b379', topic: 'us', section: 'waves', concept: 'speed-medium', by: 'kw' },
  { q: 'b380', topic: 'us', section: 'waves', concept: 'resolution-owners', by: 'tag' },
  { q: 'b381', topic: 'us', section: 'attenuation', concept: 'attenuation-rule', by: 'kw' },
  { q: 'b382', topic: 'us', section: 'impedance', concept: 'refraction-speed', by: 'kw' },
  { q: 'b383', topic: 'us', section: 'transducer', concept: 'nyquist', by: 'kw' },
  { q: 'b410', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'tag' },
  { q: 'b411', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b412', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b413', topic: 'us', section: 'doppler', concept: 'resolution-owners', by: 'tag' },
  { q: 'b422', topic: 'us', section: 'doppler', concept: 'resolution-owners', by: 'tag' },
  { q: 'b446', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b449', topic: 'us', section: 'waves', concept: 'speed-medium', by: 'kw' },
  { q: 'x51', topic: 'us', section: 'transducer', concept: 'resolution-owners', by: 'kw' },
  { q: 'x56', topic: 'us', section: 'impedance', concept: 'impedance-mismatch', by: 'kw' },
  { q: 'b28', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'tag' },
  { q: 'b29', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'tag' },
  { q: 'b30', topic: 'safety', section: 'effects', concept: 'det-vs-stoch', by: 'tag' },
  { q: 'b51', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b56', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b104', topic: 'safety', section: 'effects', concept: 'dose-chain', by: 'tag' },
  { q: 'b144', topic: 'safety', section: 'quantities', by: 'kw' },
  { q: 'b145', topic: 'safety', section: 'quantities', by: 'kw' },
  { q: 'b178', topic: 'safety', section: 'quantities', by: 'kw' },
  { q: 'b188', topic: 'safety', section: 'quantities', by: 'kw' },
  { q: 'b189', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'tag' },
  { q: 'b190', topic: 'safety', section: 'legislation', concept: 'irr-areas', by: 'tag' },
  { q: 'b204', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b213', topic: 'safety', section: 'legislation', by: 'kw' },
  { q: 'b214', topic: 'safety', section: 'staff', by: 'kw' },
  { q: 'b223', topic: 'safety', section: 'limits', by: 'kw' },
  { q: 'b224', topic: 'safety', section: 'effects', concept: 'dose-chain', by: 'tag' },
  { q: 'b230', topic: 'safety', section: 'legislation', concept: 'pregnancy-rule', by: 'kw' },
  { q: 'b258', topic: 'safety', section: 'legislation', by: 'kw' },
  { q: 'b260', topic: 'safety', section: 'effects', concept: 'risk-numbers', by: 'tag' },
  { q: 'b274', topic: 'safety', section: 'legislation', concept: 'dose-chain', by: 'tag' },
  { q: 'b276', topic: 'safety', section: 'legislation', concept: 'det-vs-stoch', by: 'tag' },
  { q: 'b277', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b306', topic: 'safety', section: 'effects', concept: 'dose-chain', by: 'tag' },
  { q: 'b307', topic: 'safety', section: 'legislation', concept: 'dose-chain', by: 'tag' },
  { q: 'b308', topic: 'safety', section: 'legislation', concept: 'no-patient-limits', by: 'tag' },
  { q: 'b336', topic: 'safety', section: 'legislation', concept: 'no-patient-limits', by: 'tag' },
  { q: 'b337', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'tag' },
  { q: 'b339', topic: 'safety', section: 'effects', concept: 'dose-chain', by: 'tag' },
  { q: 'b340', topic: 'safety', section: 'effects', concept: 'dose-chain', by: 'tag' },
  { q: 'b366', topic: 'safety', section: 'effects', concept: 'dose-chain', by: 'tag' },
  { q: 'b367', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'tag' },
  { q: 'b368', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b369', topic: 'safety', section: 'radiobiology', concept: 'apron-scatter', by: 'kw' },
  { q: 'b396', topic: 'safety', section: 'legislation', concept: 'irr-areas', by: 'tag' },
  { q: 'b397', topic: 'safety', section: 'legislation', concept: 'no-patient-limits', by: 'tag' },
  { q: 'b398', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b421', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b423', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b428', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b433', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'b434', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'tag' },
  { q: 'b437', topic: 'safety', section: 'effects', concept: 'det-vs-stoch', by: 'tag' },
  { q: 'b452', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'x38', topic: 'safety', section: 'quantities', concept: 'dose-chain', by: 'kw' },
  { q: 'x40', topic: 'safety', section: 'legislation', concept: 'irmer-roles', by: 'kw' },
  { q: 'x55', topic: 'safety', section: 'staff', by: 'kw' },
]

/**
 * Sections that legitimately have no questions.
 *
 * E6 exists because a primer with no practice gate teaches something the
 * candidate can never be tested on: Topic.tsx hides the gate when the pool is
 * empty, so they read it, nod, and move on with no way to check. Seven
 * sections were in that state. Five have been filled by hand from questions
 * the resolver had misfiled. These two could not be, and a waiver is a claim
 * that the BANK holds nothing on the subject, not that nobody got round to it.
 */
export const ALLOW_EMPTY: string[] = [
  /* Nothing in the 21 digital questions is about processing. They are about CR
     readout, panel construction, matrix and bit depth, dynamic range and MTF.
     Histogram analysis, edge enhancement and flat-field correction are taught
     because the exam asks them; this bank has simply never recalled one. */
  'digital/processing',
  /* Every one of the 20 fluoroscopy questions is about the intensifier, ABC,
     DSA or dose. None is about the live chain as a chain: under-couch versus
     over-couch geometry, the screening room, where the operator stands. */
  'fluoro/chain',
]
