// GENERATED by scripts/build-hero-frames.mjs — do not edit by hand.
// Run `npm run frames` after adding or removing files under
// public/images/hero/skull/. `npm run dev` and `npm run build` run it for you.

export interface HeroLadder {
  /** Square edge in px. Equals the directory name. */
  size: number;
  /** Root-absolute paths, in display order. MUST go through assetUrl().
      The ?v= cache-buster is appended at the point of use, not stored here. */
  frames: string[];
  /** Where each frame sits around the turn, normalised to 0..1, parallel to
      the frames array. Read from the number in the filename, so unevenly
      spaced sets rotate at a constant angular speed instead of lurching
      across the wide gaps. */
  positions: number[];
}

export interface HeroFrames {
  /** 8 hex chars over every (relative path, byte size) pair. '' when empty. */
  rev: string;
  /** Root-absolute. Referenced from index.html too, so it carries NO ?v=. */
  poster: string | null;
  chest: string | null;
  /** Ascending by size. Empty ⇒ the hero does not exist. */
  ladders: HeroLadder[];
}

export const HERO_FRAMES: HeroFrames = {
  rev: '08ec84f0',
  poster: "/images/hero/skull/poster.webp",
  chest: "/images/hero/chest.webp",
  ladders: [
    {
      size: 480,
      frames: [
        "/images/hero/skull/480/skull-0022.webp",
        "/images/hero/skull/480/skull-0068.webp",
        "/images/hero/skull/480/skull-0135.webp",
        "/images/hero/skull/480/skull-0158.webp",
        "/images/hero/skull/480/skull-0180.webp",
        "/images/hero/skull/480/skull-0202.webp",
        "/images/hero/skull/480/skull-0225.webp",
        "/images/hero/skull/480/skull-0248.webp",
        "/images/hero/skull/480/skull-0292.webp",
        "/images/hero/skull/480/skull-0338.webp",
      ],
      positions: [0, 0.14557, 0.35759, 0.43038, 0.5, 0.56962, 0.64241, 0.71519, 0.85443, 1],
    },
    {
      size: 720,
      frames: [
        "/images/hero/skull/720/skull-0022.webp",
        "/images/hero/skull/720/skull-0068.webp",
        "/images/hero/skull/720/skull-0135.webp",
        "/images/hero/skull/720/skull-0158.webp",
        "/images/hero/skull/720/skull-0180.webp",
        "/images/hero/skull/720/skull-0202.webp",
        "/images/hero/skull/720/skull-0225.webp",
        "/images/hero/skull/720/skull-0248.webp",
        "/images/hero/skull/720/skull-0292.webp",
        "/images/hero/skull/720/skull-0338.webp",
      ],
      positions: [0, 0.14557, 0.35759, 0.43038, 0.5, 0.56962, 0.64241, 0.71519, 0.85443, 1],
    },
  ],
};
